"""add_job_fields

Revision ID: 254b4c9bb0f1
Revises: fd28c92a77e4
Create Date: 2026-06-06 13:25:43.560679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254b4c9bb0f1'
down_revision: Union[str, Sequence[str], None] = 'fd28c92a77e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('cleaning_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('preferred_date', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('has_pets', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('has_allergies', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('special_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'special_notes')
    op.drop_column('jobs', 'has_allergies')
    op.drop_column('jobs', 'has_pets')
    op.drop_column('jobs', 'preferred_date')
    op.drop_column('jobs', 'cleaning_type')
    # ### end Alembic commands ###
