"""add completed jobs count to user

Revision ID: 51f07608f518
Revises: e62facf4aa58
Create Date: 2026-06-11 07:25:37.944570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f07608f518'
down_revision: Union[str, Sequence[str], None] = 'e62facf4aa58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('completed_jobs', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'completed_jobs')
    # ### end Alembic commands ###
